import DesignIcon from '../../../../shared/components/ui/DesignIcon'
import type { CatalogCourse } from '../../types/catalog'
import type { CourseAcademicDetails } from '../../types/details'
import CourseLaboratory from './CourseLaboratory'
const allocation = [{ label: 'Código Prático', value: 48 }, { label: 'Engenharia', value: 27 }, { label: 'Projetos', value: 15 }, { label: 'Fundamentos', value: 10 }]
export default function CourseOverview({ course, details }: { course: CatalogCourse; details?: CourseAcademicDetails }) {
  if (!details) return <section className="course-white-panel"><p className="academic-kicker">Matriz acadêmica · Formação</p><h2>Conheça a formação em {course.title}</h2><p className="course-body-copy">{course.description}</p><h3 className="course-fallback-title">Principais temas de estudo</h3><ul className="course-fallback-list">{course.lessons.map(lesson => <li key={lesson}>{lesson}</li>)}</ul></section>
  return <><div className="course-overview-grid"><article className="course-editorial course-white-panel"><p className="academic-kicker">Matriz acadêmica · Formação</p><h2>{details.overviewTitle}</h2>{details.paragraphs.map(paragraph => <p className="course-body-copy" key={paragraph}>{paragraph}</p>)}<dl className="course-outcomes">{details.metrics.map(metric => <div key={metric.label}><dd>{metric.value}</dd><dt>{metric.label}</dt></div>)}</dl></article><CourseLaboratory /></div><div className="course-impact-grid"><section className="course-white-panel"><div className="course-section-title"><span className="course-icon-box"><DesignIcon name="detail-imgContainer12" /></span><div><h2>Áreas Principais de Estudo</h2><p>Eixos temáticos desenvolvidos no ciclo formativo</p></div></div><ul className="course-study-areas">{details.studies.map(study => <li key={study.title}><DesignIcon name={study.icon} /><div><h3>{study.title}</h3><p>{study.description}</p></div></li>)}</ul></section><section className="course-white-panel course-careers"><div className="course-section-title"><span className="course-icon-box"><DesignIcon name="detail-imgContainer13" /></span><div><h2>Atuação Profissional e Mercado</h2><p>Posições ocupadas por egressos em empresas globais e scale-ups</p></div></div><ul className="course-career-grid">{details.careers.map(career => <li key={career.title}><h3>{career.title}</h3><p>{career.description}</p></li>)}</ul><div className="course-allocation"><div><h3>Alocação de Tempo por Atividade Pedagógica</h3><span>{details.hours.toLocaleString('pt-BR')} horas</span></div><div className="allocation-bar" aria-hidden="true">{allocation.map((item, index) => <span key={item.label} className={'allocation-' + index} style={{ flex: item.value }} />)}</div><ul>{allocation.map((item, index) => <li key={item.label}><span className={'allocation-' + index} />{item.label} {item.value}%</li>)}</ul></div></section></div></>
}
